# Generated by Django 4.2 on 2023-06-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
