# Generated by Django 4.1.5 on 2023-06-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_feature_otp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feature',
            table='register1',
        ),
    ]
